//res file generated by ds-servers.com
//visit ds-servers.com
maps/blimpboom.res
overviews/blimpboom.txt
overviews/blimpboom.bmp
sprites/aexplo.spr
sprites/xsmoke1.spr
sprites/bexplo.spr
sprites/fire.spr
sprites/redflare1.spr
sprites/blueflare1.spr
sprites/yelflare1.spr
sprites/wsplash3.spr
sound/weapons/explode3.wav
sound/ambience/biggun3.wav
sound/ambience/blimpboom/mosquito.wav
sound/ambience/cricket.wav
sound/ambience/steamjet1.wav
sound/ambience/blimpboom/lights.wav
sound/ambience/bigwarning.wav
sound/ambience/burning3.wav
decals.wad
halflife.wad
liquids.wad
xeno.wad

gfx/env/hbbk.tga
gfx/env/hbdn.tga
gfx/env/hbft.tga
gfx/env/hblf.tga
gfx/env/hbrt.tga
gfx/env/hbup.tga
sprites/muzzleflash3.spr