//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/blimpboom.html
halflife.wad
liquids.wad
xeno.wad
decals.wad
sound/ambience/cricket.wav
sprites/fire.spr
sound/ambience/biggun3.wav
sprites/xsmoke1.spr
sprites/wsplash3.spr
sound/ambience/bigwarning.wav
sprites/yelflare1.spr
sound/ambience/steamjet1.wav
sound/weapons/explode3.wav
sound/ambience/burning3.wav
sprites/muzzleflash3.spr
sprites/blueflare1.spr
sprites/redflare1.spr
sprites/bexplo.spr
sprites/aexplo.spr
sound/ambience/blimpboom/mosquito.wav
sound/ambience/blimpboom/lights.wav
gfx/env/hbbk.tga
gfx/env/hbdn.tga
gfx/env/hbft.tga
gfx/env/hblf.tga
gfx/env/hbrt.tga
gfx/env/hbup.tga
maps/blimpboom.bsp
