//res file generated by ds-servers.com
//visit ds-servers.com
maps/crossfire_upgrade.res
overviews/crossfire_upgrade.txt
overviews/crossfire_upgrade.bmp
sprites/glow01.spr
sound/weapons/sbarrel1.wav
sound/ambience/alarm_main.wav
sound/ambience/jetflyby1.wav
sound/weapons/mortarhit.wav
sound/debris/beamstart11.wav
sound/weapons/electro5.wav
sound/rings2.wav
sound/rings1.wav
halflife.wad
xeno.wad

sprites/steam1.spr
sprites/muzzleflash1.spr