name: Release tagged commit.

on:
  push:
    tags:
      - '**'

jobs:
  PRINT_TAG_NAME:
    runs-on: ubuntu-latest
    steps:
      - name: GET TAG NAME
        run: echo ${{ github.ref_name }}
  PUBLISH_PRE-RELEASE:
    runs-on: ubuntu-latest
    steps:
      - name: CREATE RELEASE
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
